const {check} = require("express-validator")

exports.store = [
    check('deskripsi_usulan').notEmpty().withMessage('Deskripsi Usulan Tidak Boleh Kosong'),
    check('tanggal_usulan').notEmpty().withMessage("Tanggal Usulan Tidak Boleh Kosong"),
    check('jenis_belanja').notEmpty().withMessage("Jenis Belanja Tidak Boleh Kosong"),
    check('kode_unit').notEmpty().withMessage("Kode Unit Tidak Boleh Kosong"),
    check('tanggal_surat').notEmpty().withMessage("Tanggal Surat Tidak Boleh Kosong"),
    check('kode_kegiatan_ut_detail').notEmpty().withMessage("Kode Kegiatan UT Detail Tidak Boleh Kosong"),
    check('nama_kegiatan_ut_detail').notEmpty().withMessage("Nama Kegiatan UT Detail Tidak Boleh Kosong"),
    check('kode_aktivitas_rkatu').notEmpty().withMessage("Kode Aktivitas RKATU Tidak Boleh Kosong"),
    check('nama_aktivitas_rkatu').notEmpty().withMessage("Nama Aktivitas RKATU Tidak Boleh Kosong"),
    check('kode_aktivitas_rkatu').notEmpty().withMessage("Kode Aktivitas RKATU Tidak Boleh Kosong"),
    check('perihal').notEmpty().withMessage("Perihal Tidak Boleh Kosong"),
    check("kode_periode").notEmpty().withMessage("Kode Periode Tidak Boleh Kosong"),
    check('tahun').notEmpty().withMessage('Tahun Tidak Kosong'),
    check('DaftarPengadaan.*.id_uang_persediaan').notEmpty().withMessage('Id Uang Persediaan Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.nama_permintaan_up').notEmpty().withMessage('Nama Permintaan UP Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.nama_penyedia').notEmpty().withMessage('Nama Penyedia Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.jenis').notEmpty().withMessage('Jenis Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.kriteria').notEmpty().withMessage('Kriteria Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.tanggal').notEmpty().withMessage('Tanggal Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.status_permintaan_up').notEmpty().withMessage('Status Permintaan UP Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.detail.*.id_uang_persediaan').notEmpty().withMessage('Id Uang Persediaan Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.detail.*.satuan_ukuran').notEmpty().withMessage('Satuan Ukuran Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.detail.*.harga_satuan').notEmpty().withMessage('Harga Satuan Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.detail.*.kuantitas').notEmpty().withMessage('Kuantitas Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.bukti.*.id_uang_persediaan').notEmpty().withMessage('Id Uang Persediaan Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.bukti.*.nama').notEmpty().withMessage('Nama Tidak Boleh Kosong'),
    check('DaftarPengadaan.*.bukti.*.bukti').notEmpty().withMessage('Bukti Tidak Boleh Kosong'),
];