const { check } = require("express-validator");

exports.getNomor = [
    check("kode_permintaan").notEmpty().withMessage("kode_permintaan harus di isi."),
    check("kode_kontrak").notEmpty().withMessage("kode_kontrak harus di isi."),
    check("id_jenis_surat").notEmpty().withMessage("id_jenis_surat harus di isi."),
    check("id_jenis_nd").notEmpty().withMessage("id_jenis_nd harus di isi."),
    check("perihal").notEmpty().withMessage("perihal harus di isi."),
    check("kode_klasifikasi").notEmpty().withMessage("kode_klasifikasi harus di isi."),
    check("nama_pembuat").notEmpty().withMessage("nama_pembuat harus di isi."),
    check("tanggal_buat").notEmpty().withMessage("tanggal_buat harus di isi."),
    check("kode_vendor").notEmpty().withMessage("kode_vendor harus di isi."),
    check("tahun").notEmpty().withMessage("tahun harus di isi."),
    check("kode_rup").notEmpty().withMessage("kode_rup harus di isi."),
    check("nomor_rup").notEmpty().withMessage("nomor_rup harus di isi."),
    check("kode_rka").notEmpty().withMessage("kode_rka harus di isi."),
    check("kode_periode").notEmpty().withMessage("kode_periode harus di isi."),
    check("no_rek").notEmpty().withMessage("no_rek harus di isi."),
    check("nomor_rekening_terpakai").notEmpty().withMessage("nomor_rekening_terpakai harus di isi."),
    check("pemilik_rekening").notEmpty().withMessage("pemilik_rekening harus di isi."),
    check("kode_bank").notEmpty().withMessage("kode_bank harus di isi."),
    check("kode_kriteria").notEmpty().withMessage("kode_kriteria harus di isi."),
    check("kode_jenis_pembayaran").notEmpty().withMessage("kode_jenis_pembayaran harus di isi."),
    check("nama_permintaan").notEmpty().withMessage("nama_permintaan harus di isi."),
    check("metode_pembayaran").notEmpty().withMessage("metode_pembayaran harus di isi."),
    check("persen").notEmpty().withMessage("persen harus di isi."),
    check("total").notEmpty().withMessage("total harus di isi."),
    check("path_spp").notEmpty().withMessage("path_spp harus di isi."),
    check("path_sptb").notEmpty().withMessage("path_sptb harus di isi."),
    check("path_rk").notEmpty().withMessage("path_rk harus di isi."),
    check("kode_unit").notEmpty().withMessage("kode_unit harus di isi."),
    check("kode_sub_unit").notEmpty().withMessage("kode_sub_unit harus di isi."),
    check("tanggal_permintaan").notEmpty().withMessage("tanggal_permintaan harus di isi."),
    check("ucr").notEmpty().withMessage("User create harus di ada.")
];

exports.store = [
    check("data").notEmpty().withMessage("data harus di isi."),
    check("data").isArray().withMessage("data harus Array."),
    check("data.*.kode_permintaan").notEmpty().withMessage("data.*.kode_permintaan harus di isi."),
    check("data.*.kode_kontrak").notEmpty().withMessage("data.*.kode_kontrak harus di isi."),
    check("data.*.perihal").notEmpty().withMessage("data.*.perihal harus di isi."),
    check("data.*.aplikasi").notEmpty().withMessage("data.*.aplikasi harus di isi."),
    check("data.*.nama_pembuat").notEmpty().withMessage("data.*.nama_pembuat harus di isi."),
    check("data.*.tanggal_buat").notEmpty().withMessage("data.*.tanggal_buat harus di isi."),
    check("data.*.kode_vendor").notEmpty().withMessage("data.*.kode_vendor harus di isi."),
    check("data.*.tahun").notEmpty().withMessage("data.*.tahun harus di isi."),
    check("data.*.kode_rup").notEmpty().withMessage("data.*.kode_rup harus di isi."),
    check("data.*.nomor_rup").notEmpty().withMessage("data.*.nomor_rup harus di isi."),
    check("data.*.nama_rup").notEmpty().withMessage("data.*.nama_rup harus di isi."),
    check("data.*.kode_rka").notEmpty().withMessage("data.*.kode_rka harus di isi."),
    check("data.*.kode_periode").notEmpty().withMessage("data.*.kode_periode harus di isi."),
    check("data.*.no_rekening_tujuan").notEmpty().withMessage("data.*.no_rekening_tujuan harus di isi."),
    check("data.*.pemilik_rekening").notEmpty().withMessage("data.*.pemilik_rekening harus di isi."),
    check("data.*.kode_bank_tujuan").notEmpty().withMessage("data.*.kode_bank_tujuan harus di isi."),
    check("data.*.nama_bank_tujuan").notEmpty().withMessage("data.*.nama_bank_tujuan harus di isi."),
    check("data.*.kode_kriteria").notEmpty().withMessage("data.*.kode_kriteria harus di isi."),
    check("data.*.kode_jenis_pembayaran").notEmpty().withMessage("data.*.kode_jenis_pembayaran harus di isi."),
    check("data.*.nama_permintaan").notEmpty().withMessage("data.*.nama_permintaan harus di isi."),
    check("data.*.metode_pembayaran").notEmpty().withMessage("data.*.metode_pembayaran harus di isi."),
    check("data.*.persen").notEmpty().withMessage("data.*.persen harus di isi."),
    check("data.*.total").notEmpty().withMessage("data.*.total harus di isi."),
    check("data.*.total_kontrak").notEmpty().withMessage("data.*.total_kontrak harus di isi."),
    check("data.*.path_spp").notEmpty().withMessage("data.*.path_spp harus di isi."),
    check("data.*.path_sptb").notEmpty().withMessage("data.*.path_sptb harus di isi."),
    check("data.*.path_rk").notEmpty().withMessage("data.*.path_rk harus di isi."),
    check("data.*.path_spk").notEmpty().withMessage("data.*.path_spk harus di isi."),
    check("data.*.path_BAST").notEmpty().withMessage("data.*.path_BAST harus di isi."),
    check("data.*.path_copy_NPWP").notEmpty().withMessage("data.*.path_copy_NPWP harus di isi."),
    check("data.*.path_e_faktur").notEmpty().withMessage("data.*.path_e_faktur harus di isi."),
    check("data.*.path_copy_halaman_depan_rekening").notEmpty().withMessage("data.*.path_copy_halaman_depan_rekening harus di isi."),
    check("data.*.kode_unit").notEmpty().withMessage("data.*.kode_unit harus di isi."),
    check("data.*.kode_sub_unit").notEmpty().withMessage("data.*.kode_sub_unit harus di isi."),
    check("data.*.akun_bas_rka").notEmpty().withMessage("data.*.akun_bas_rka harus di isi."),
    check("data.*.akun_sub_realisasi").notEmpty().withMessage("data.*.akun_bas_realisasi harus di isi."),
    check("data.*.tanggal_permintaan").notEmpty().withMessage("data.*.tanggal_permintaan harus di isi."),
    // check("data.*.data_pengusulan").notEmpty().isIn(['TRANSAKSI-HISTORIS','TRANSAKSI-BARU']).withMessage("data.*.data_pengusulan harus di isi. ['TRANSAKSI-HISTORIS','TRANSAKSI-BARU']"),
    check("data.*.ucr").notEmpty().withMessage("data.*.User create harus di ada.")
];

exports.storeOne = [
    check("kode_permintaan").notEmpty().withMessage("kode_permintaan harus di isi."),
    check("kode_kontrak").notEmpty().withMessage("kode_kontrak harus di isi."),
    check("perihal").notEmpty().withMessage("perihal harus di isi."),
    check("aplikasi").notEmpty().withMessage("aplikasi harus di isi."),
    check("nama_pembuat").notEmpty().withMessage("nama_pembuat harus di isi."),
    check("tanggal_buat").notEmpty().withMessage("tanggal_buat harus di isi."),
    check("kode_vendor").notEmpty().withMessage("kode_vendor harus di isi."),
    check("tahun").notEmpty().withMessage("tahun harus di isi."),
    check("kode_rup").notEmpty().withMessage("kode_rup harus di isi."),
    check("nomor_rup").notEmpty().withMessage("nomor_rup harus di isi."),
    check("nama_rup").notEmpty().withMessage("nama_rup harus di isi."),
    check("kode_rka").notEmpty().withMessage("kode_rka harus di isi."),
    check("kode_periode").notEmpty().withMessage("kode_periode harus di isi."),
    check("no_rekening_tujuan").notEmpty().withMessage("no_rekening_tujuan harus di isi."),
    check("pemilik_rekening").notEmpty().withMessage("pemilik_rekening harus di isi."),
    check("kode_bank_tujuan").notEmpty().withMessage("kode_bank_tujuan harus di isi."),
    check("nama_bank_tujuan").notEmpty().withMessage("nama_bank_tujuan harus di isi."),
    check("kode_kriteria").notEmpty().withMessage("kode_kriteria harus di isi."),
    check("kode_jenis_pembayaran").notEmpty().withMessage("kode_jenis_pembayaran harus di isi."),
    check("nama_permintaan").notEmpty().withMessage("nama_permintaan harus di isi."),
    check("metode_pembayaran").notEmpty().withMessage("metode_pembayaran harus di isi."),
    check("persen").notEmpty().withMessage("persen harus di isi."),
    check("total").notEmpty().withMessage("total harus di isi."),
    check("total_kontrak").notEmpty().withMessage("total_kontrak harus di isi."),
    check("path_spp").notEmpty().withMessage("path_spp harus di isi."),
    check("path_sptb").notEmpty().withMessage("path_sptb harus di isi."),
    check("path_rk").notEmpty().withMessage("path_rk harus di isi."),
    check("path_spk").notEmpty().withMessage("path_spk harus di isi."),
    check("path_BAST").notEmpty().withMessage("path_BAST harus di isi."),
    check("path_copy_NPWP").notEmpty().withMessage("path_copy_NPWP harus di isi."),
    check("path_e_faktur").notEmpty().withMessage("path_e_faktur harus di isi."),
    check("path_copy_halaman_depan_rekening").notEmpty().withMessage("path_copy_halaman_depan_rekening harus di isi."),
    check("kode_unit").notEmpty().withMessage("kode_unit harus di isi."),
    check("nama_unit").notEmpty().withMessage("nama_unit harus di isi."),
    check("kode_sub_unit").notEmpty().withMessage("kode_sub_unit harus di isi."),
    check("tanggal_permintaan").notEmpty().withMessage("tanggal_permintaan harus di isi."),
    check("akun_bas_rka").notEmpty().withMessage("akun_bas_rka harus di isi."),
    check("akun_bas_realisasi").notEmpty().withMessage("akun_bas_realisasi harus di isi."),
    // check("data_pengusulan").notEmpty().isIn(['TRANSAKSI-HISTORIS','TRANSAKSI-BARU']).withMessage("data_pengusulan harus di isi. ['TRANSAKSI-HISTORIS','TRANSAKSI-BARU']"),
    check("ucr").notEmpty().withMessage("User create harus di ada.")
];

exports.UpdateStatus = [
    check("kode_permintaan").notEmpty().withMessage("kode_permintaan harus di isi."),
    check("kode_kontrak").notEmpty().withMessage("kode_kontrak harus di isi."),
    check("kode_vendor").notEmpty().withMessage("kode_vendor harus di isi."),
    check("status").notEmpty().withMessage("status harus di isi."),
];

exports.getNomorSPM = [
    check("kode_permintaan").notEmpty().withMessage("kode_permintaan harus di isi."),
    check("kode_kontrak").notEmpty().withMessage("kode_kontrak harus di isi."),
    check("kode_vendor").notEmpty().withMessage("kode_vendor harus di isi."),
    check("aplikasi").notEmpty().withMessage("aplikasi harus di isi."),
    check("sifat_surat").notEmpty().withMessage("sifat_surat harus di isi."),
    check("id_jenis_surat").notEmpty().withMessage("id_jenis_surat harus di isi."),
    check("id_jenis_nd").notEmpty().withMessage("id_jenis_nd harus di isi."),
    check("kode_klasifikasi").notEmpty().withMessage("kode_klasifikasi harus di isi."),
    check("kode_sub_unit").notEmpty().withMessage("kode_sub_unit harus di isi."),
    check("nama_pembuat").notEmpty().withMessage("nama_pembuat harus di isi."),
    check("tanggal_buat").notEmpty().withMessage("tanggal_buat harus di isi."),
    check("kode_unit").notEmpty().withMessage("kode_unit harus di isi."),
    check("tahun").notEmpty().withMessage("tahun harus di isi."),
    check("ucr").notEmpty().withMessage("ucr harus di isi."),
]
